networks:
  server:
  client :    
services:
  backend:
      build: Backend
      container_name: backend
      restart: on-failure
      environment:
          - DATABASE_HOST=database
          - DATABASE_USER=user
          - DATABASE_PASSWORD=password
          - DATABASE_NAME=casecoolors
          - DATABASE_PORT=3306    
      depends_on:
          - database
      networks:
          - client
          - server
  frontend:
      build: Frontend
      container_name: frontend
      depends_on:
          - backend
      networks:
          - client
  database:
      container_name: database
      image: mysql/mysql-server:8.0.24
      restart: on-failure
      environment:
          - MYSQL_ROOT_PASSWORD=CaseCoolors123
          - MYSQL_DATABASE=casecoolors
          - MYSQL_USER=user
      volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
          - server
  reverse-poxy:
      image: nginx
      container_name: reverse-poxy
      depends_on:
          - frontend
          - backend
          - database
      volumes: 
          - ./nginx.conf:/etc/nginx/nginx.conf
      restart: on-failure
      networks:
          - client
      ports:
          - "80:80"
